### ISSUE TITLE
load_player_stats() for defensive players

### ISSUE THREAD

**Issue by TheMathNinja** [nflverse/nflfastR#205]
I'm wondering if we can get a load_player_stats() and calculate_player_stats() for defensive positions.

Numbers like:
Solos
TWAs
Assists
TFLs
QB Hits
FF
FR
FR Yards
Sacks
Sack Yards
Safeties
etc.

Thanks

**Comment by guga31bb** [comment]
We probably won't get to this for awhile (if ever), so I'm labeling this with "help wanted".

If anyone wants to contribute, this might be a good place to start- see [this function](https://github.com/mrcaseb/nflfastR/blob/master/R/aggregate_game_stats.R) which does everything for offensive players.

**Comment by TheMathNinja** [comment]
Whoa. 450 lines is no joke.

**Comment by guga31bb** [comment]
Closing this as it is now basically a duplicate of #235
