### ISSUE TITLE
Ability to silence messages from functions

### ISSUE THREAD

**Issue by tanho63** [nflverse/nflfastR#233]
Looking to use/import the package in another package and would like option to silence some of the usethis-built messages - possibly with a .quiet argument which can default to FALSE?

**Comment by mrcaseb** [comment]
Good point! I will think about a good solution and implement it.

**Comment by mrcaseb** [comment]
I am thinking about silencing the messages automatically if called from inside another package (like the dplyr summarise inform messages). This way would make sure you don't even have to add another argument.

**Comment by tanho63** [comment]
YES YES YES

**Comment by guga31bb** [comment]
Is this still relevant with the existence of `nflreadr` or can it be closed?

**Comment by tanho63** [comment]
Thank you for your service, issue #233. We appreciated your inspiration and your memory will live on in `nflreadr`. 

Love, Tan
