### ISSUE TITLE
Additional columns for calculate_player_stats()

### ISSUE THREAD

**Issue by TheMathNinja** [nflverse/nflfastR#235]
I was wondering if you might be willing to include a few additional columns for calculate_player_stats()?

Would love the following included:
* Fumbles (not just Fumbles Lost)
* Sack Yards (not just Sacks)
* Own fumble recoveries (times a player recovered his own team's fumble)
* Own fumble recovery yardages (total yards off such recoveries)
* Own fumble recovery TDs
* Penalties
* Penalty Yards

Thanks so much!

**Comment by guga31bb** [comment]
Tagging this with help wanted since we probably won't get to this soon (if ever). Some of these would be pretty hard to figure out (especially the penalty ones).

**Comment by mrcaseb** [comment]
Progress:

- [ ] Fumbles (not just Fumbles Lost)
- [ ] Sack Yards (not just Sacks)
- [ ] Own fumble recoveries (times a player recovered his own team's fumble)
- [ ] Own fumble recovery yardages (total yards off such recoveries)
- [ ] Own fumble recovery TDs
- [ ] Penalties
- [ ] Penalty Yards

**Comment by tanho63** [comment]
Tacking some ffscrapr-related requests

Return:
- separated kick and punt return yards, TDs, and fumbles

Basic IDP:
- solo, assisted tackles, combined tackles
- sacks
- fumbles forced
- fumbles recovered
- pass defended
- interception

**Comment by jkope892** [comment]
Finally getting to play with the new upgrades since last season and load_player_stats() is an absolute dream!

I was wondering how you guys feel about adding columns for CPOE/Pass OE and dropbacks?  

I know adding a straight up dropbacks column might be a pain b/c the fx gets official stats, so I thought maybe if we could just get columns for scrambles/spikes instead then we'd be able to calculate DB's ourselves.  There are literally no data sources that include DB's so this would be awesome.

As always, a million thanks for the work you guys put into this!

**Comment by TheMathNinja** [comment]
I'm realizing that even more importantly than ignoring return fumbles, `calculate_player_stats() `is also ignoring aborted-snap fumbles, which is important to see in order to total player fumbles. For example, https://www.nfl.com/players/lamar-jackson/stats/ shows Lamar Jackson had 9 fumbles in 2019. But summing fumbles in `calculate_player_stats()` only amounts to 7 total fumbles. 

I tracked down the two culprits to 
2413 | 2019_07_BAL_SEA and 201 | 2019_15_NYJ_BAL, 

Lamar Jackson fumbles twice in week 7 and once in week 15 but `calculate_player_stats()` shows 1 in Week 7 and 0 in Week 15.  Wondering what the best call is here....perhaps an other_fumbles column?

**Comment by TheMathNinja** [comment]
> Progress:
> 
> * [x]  Fumbles (not just Fumbles Lost)
> * [x]  Sack Yards (not just Sacks)
> * [ ]  Own fumble recoveries (times a player recovered his own team's fumble)
> * [ ]  Own fumble recovery yardages (total yards off such recoveries)
> * [ ]  Own fumble recovery TDs
> * [ ]  Penalties
> * [ ]  Penalty Yards

Hey @christianlohr9 what do you think about just copy-pasting your def code to knock out this whole thing with one PR? 🤔

**Comment by mrcaseb** [comment]
This should be implemented by `nflfastR::calculate_player_stats_def()`
