### ISSUE TITLE
2018_01_ATL_PHI:  All 3rd Down and 4th Down Statistics Are "0"

### ISSUE THREAD

**Issue by JoeMarino2021** [nflverse/nflfastR#246]
Let's load 2018's data.  Then, let's look at the first game of the year.
```
library(tidyverse)
dfYearpbp <- nflfastR::load_pbp(2018)
dfYearpbp %>% filter(game_id == "2018_01_ATL_PHI") %>% select(third_down_converted, third_down_failed, fourth_down_converted, fourth_down_failed, down, desc) %>% View("ATL vs PHI 3rd and 4th Down Variables")
```

If you are using RStudio, you'll be looking at a data frame of selected variables from the first game of the year.  All of the 3rd and 4th down variables are zero.  Some of these should be 1.

Do you know what's going on here?

**Comment by guga31bb** [comment]
Probably just this one game that's messed up. We fixed some columns (https://github.com/nflverse/nflfastR/issues/32) but looks like there's more
