### ISSUE TITLE
2018_01_NYJ_DET:  Drive 7 Should be Drive 7 and Drive 8 after Interception that was Fumbled

### ISSUE THREAD

**Issue by JoeMarino2021** [nflverse/nflfastR#247]
Let's load up 2018's data, and then take a look at Week 1's contest between the Jet's and Lions

```
library(tidyverse)
dfYearpbp <- nflfastR::load_pbp(2018)
dfYearpbp %>% filter(game_id == "2018_01_NYJ_DET") %>% select(play_id, posteam, fixed_drive, qtr, down, ydstogo, desc) %>% View("NYJ vs DET 2018")
```

Look at Drive 7.  On `Play_ID 1101`, this happens:
	
`(12:08) (Shotgun) 9-M.Stafford pass short right intended for 13-T.Jones INTERCEPTED by 22-T.Johnson at NYJ 23. 22-T.Johnson to NYJ 30 for 7 yards (19-K.Golladay). FUMBLES (19-K.Golladay), RECOVERED by DET-19-K.Golladay at NYJ 33. 19-K.Golladay to NYJ 33 for no gain (50-F.Luvu). NYJ-22-T.Johnson was injured during the play.`

In the official NFL statistics, they create a new drive here, so that Detroit would have drives 7 and 8.  In the NFLFastR pbp db it is listed as only drive 7 for Detroit.  (`Play_ID 1138` should begin Detroit's new drive, Drive 8 for the game).  I'd like to see this changed to match the official statistics.

Thanks for all of the fantastic work!

**Comment by JoeMarino2021** [comment]
Also, note Play_ID=1930 in 2018_17_LAC_DEN for the same issue.  A fumbled interception that results in recovery by the original offense.  Play_ID=1978 should have started a new drive for Denver.

**Comment by guga31bb** [comment]
> Also, note Play_ID=1930 in 2018_17_LAC_DEN for the same issue. A fumbled interception that results in recovery by the original offense. Play_ID=1978 should have started a new drive for Denver.

Yep, see https://github.com/nflverse/nflfastR/pull/245#issuecomment-861488646

**Comment by JoeMarino2021** [comment]
Dang!  You are fast!  I guess they don't call it NFLFastR for nothing!  I was just coming back here to edit my comment to note that you noted you already found that play!

**Comment by JoeMarino2021** [comment]
I guess I might suggest looking for fumbled fumble recoveries to see if those are not currently coded for.

**Comment by JoeMarino2021** [comment]
Did you guys look for fumbles back to the offense after a defense recovered a fumble?  Will those begin new drives?  I would think they would, although I am not sure.
