### ISSUE TITLE
2018_09_PIT_BAL:  Final Play Shows -2 Yards Gained, It Should Be -3 Yards Gained

### ISSUE THREAD

**Issue by JoeMarino2021** [nflverse/nflfastR#248]
On the final play of `2018_09_PIT_BAL` (`Play_ID 4347`), the yardage gained shows as -2.  I believe the yardage gained should be -3 (+7 -8 -2).

`(:08) (Shotgun) 5-J.Flacco pass short middle to 15-M.Crabtree to BAL 30 for 7 yards. Lateral to 37-J.Allen to BAL 22 for -8 yards. Lateral to 13-J.Brown to BAL 20 for -2 yards. PENALTY on BAL-13-J.Brown, Illegal Forward Pass, 0 yards, enforced at BAL 20.`

Thanks for all the cool code!

**Comment by JoeMarino2021** [comment]
Here is an NFL JSON source for data from this game:

https://static.nfl.com/liveupdate/game-center/2018110400/2018110400_gtd.json

Here is the `players` dictionary from that JSON for the play in question:
```
'players': {'0': [{'sequence': 1,
    'clubcode': 'BAL',
    'playerName': None,
    'statId': 9,
    'yards': 0.0}],
  '00-0031577': [{'sequence': 7,
    'clubcode': 'BAL',
    'playerName': 'J.Allen',
    'statId': 23,
    'yards': -8.0},
   {'sequence': 8,
    'clubcode': 'BAL',
    'playerName': 'J.Allen',
    'statId': 113,
    'yards': -8.0}],
  '00-0031051': [{'sequence': 9,
    'clubcode': 'BAL',
    'playerName': 'J.Brown',
    'statId': 23,
    'yards': -2.0},
   {'sequence': 10,
    'clubcode': 'BAL',
    'playerName': 'J.Brown',
    'statId': 113,
    'yards': -2.0},
   {'sequence': 11,
    'clubcode': 'BAL',
    'playerName': 'J.Brown',
    'statId': 93,
    'yards': 0.0}],
  '00-0026986': [{'sequence': 4,
    'clubcode': 'BAL',
    'playerName': 'M.Crabtree',
    'statId': 21,
    'yards': 7.0},
   {'sequence': 5,
    'clubcode': 'BAL',
    'playerName': 'M.Crabtree',
    'statId': 115,
    'yards': 0.0},
   {'sequence': 6,
    'clubcode': 'BAL',
    'playerName': 'M.Crabtree',
    'statId': 113,
    'yards': 0.0}],
  '00-0026158': [{'sequence': 2,
    'clubcode': 'BAL',
    'playerName': 'J.Flacco',
    'statId': 15,
    'yards': -3.0},
   {'sequence': 3,
    'clubcode': 'BAL',
    'playerName': 'J.Flacco',
    'statId': 111,
    'yards': 7.0}]}}
```

### Decoding the players dictionary
J.Allen, `Stat IDs  23` (`Pass Reception Yards, No Reception`) and `113` (`Yardage Gained After the Catch`), both listed as -8 yards.
J.Brown, `Stat IDs 23, 113, and 93` (`Penalty`), first two listed as -2 yards, the penalty listed as zero yards.
M.Crabtree, `Stat IDs 21` (`Pass Reception Yards`), `115` (`Pass Target`), and `113`, listed as 7, 0 (just a pass target), and 0 yards.
J.Flacco, `Stat IDs 15` (`Passing Yards`) and `111` (`Pass Length, Completion`), listed as -3 yards and 7 yards.

### Getting the right yardage?
`Stat ID 113` seems a little confusing, but we might still have enough info here to piece together the correct yardage for this play.  It looks like poor Joe Flacco watched his 7-yard pass completion turn into -3 passing yards as the yardage lost by the laterals were charged against his passing yards.  Allen and Brown lost 10 total yards in plays called "receptions/no reception", AKA laterals, for making themselves available for backwards passes during this desperation play.  Crabtree makes out pretty good here, gaining 7 receiving yards and then staying out of the rest of the play.

It seems like a couple of different ways can lead us to -3 yards for this play.  Looking at Flacco's passing yards alone will give us the number we need.  Also, if we add up all of the `Stat ID 23` and `21` items we will get -3 yards (7 - 8 - 2).  I'm not sure if the NFL is very consistent as they fill out these items, but if they are, then either of these two approaches will suffice to come up with the correct tally.

### Video
https://www.youtube.com/watch?v=Dw8HoHQ7m2g  Starting at 10:07, you can watch the play in question.  After Flacco's 7 yard pass to Crabtree, everything else "official" about this play is wrong.  How does the NFL score this stuff?  Apparently the part where Crabtree is running with the ball past the 30 yard line didn't happen?

Hopefully this helps someone out there!

**Comment by mrcaseb** [comment]
The variable `yards_gained` is broken for rare plays like this. We have discussed this multiple times and added new variables to fix this. See https://github.com/nflverse/nflfastR/issues/115#issuecomment-777330051

It typically happens in plays with laterals. Those plays have correct yardage either in `passing_yards` if the first action of the play was a pass or `rushing_yards` combinded with `lateral_rushing_yards` if the first action of the play was a rush (very rare).

You can work with this by comparing `yards_gained` with `passing_yards` or with `rushing_yards + lateral_rushing_yards`

The plays where those values are not the same have correct yardage in `passing_yards` or `rushing_yards + lateral_rushing_yards`

``` r
nflfastR::fast_scraper("2018_09_PIT_BAL") %>% 
  dplyr::filter(play_id == 4347) %>% 
  dplyr::select(game_id, play_id, yards_gained, passing_yards, rushing_yards)

#> # A tibble: 1 x 5
#>   game_id         play_id yards_gained passing_yards rushing_yards
#>   <chr>             <dbl>        <dbl>         <dbl>         <dbl>
#> 1 2018_09_PIT_BAL    4347           -2            -3            NA
```

<sup>Created on 2021-07-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
