### ISSUE TITLE
NFL url's to scrap data from -apparently- have changed

### ISSUE THREAD

**Issue by 0lorak** [nflverse/nflfastR#258]
It seems that widgets below -the example for Super Bowl LV- are not available anymore for the 2021 season.

https://nflcdns.nfl.com/widget/gc/2011/tabs/cat-post-boxscore?gameId=2021020700
https://nflcdns.nfl.com/widget/gc/2011/tabs/cat-post-playbyplay?gameId=2021020700

This url, https://nflcdns.nfl.com/widget/gc/2011/tabs/cat-post-boxscore?gameId=2021080551, should display the boxscore of  the 2021 Hall of Fame game but is not available. 

Do you have an idea of the new url's to get data from? 
Maybe also of  a new gameId format?

**Comment by guga31bb** [comment]
Data can be accessed through the package. Closing this because this shouldn't affect the functionality of the package
