### ISSUE TITLE
Feature Request 'GSIS_game_key' column

### ISSUE THREAD

**Issue by mm0708** [nflverse/nflfastR#267]
Request gsis game_key column is added to nflfastR outputs in order to make joining model onto other data sources easier.

**Comment by mrcaseb** [comment]
I am not 100% sure what `'GSIS_game_key'` is but it might be the `old_game_id` in the schedule data?

``` r
nflfastR::fast_scraper_schedules(2021) |> 
  dplyr::select(game_id, old_game_id)
#> # A tibble: 272 x 2
#>    game_id         old_game_id
#>    <chr>           <chr>      
#>  1 2021_01_DAL_TB  2021090900 
#>  2 2021_01_PHI_ATL 2021091200 
#>  3 2021_01_PIT_BUF 2021091201 
#>  4 2021_01_NYJ_CAR 2021091202 
#>  5 2021_01_MIN_CIN 2021091203 
#>  6 2021_01_SF_DET  2021091204 
#>  7 2021_01_JAX_HOU 2021091205 
#>  8 2021_01_SEA_IND 2021091206 
#>  9 2021_01_ARI_TEN 2021091207 
#> 10 2021_01_LAC_WAS 2021091208 
#> # ... with 262 more rows
```

<sup>Created on 2021-08-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by mm0708** [comment]
old_game_id is the gsis_game_id column in NFL's NGS system, gsis_game_key is a unique five digit number assigned to each game example: 55577. Each game has both a gsis game id which looks similar to the game date and a five digit key. Sources such as PFF provide game key but not id, so to make joining on PFF data easier it would be nice if nflfastR was able to provide the game key as well as id since they should both be available through the same source. If not I apologize for sending you on a wild goose chase. It's possible to join them now through team and game date, but this would be much more direct.

**Comment by mrcaseb** [comment]
We know ways to do this and will probably add those ids in the next weeks. Stay tuned

**Comment by mm0708** [comment]
Any update on this?

**Comment by mrcaseb** [comment]
> 
> 
> Any update on this?

The data is available now but you need to run nflreadr because nflfastR isn't updated yet. Here is an example for the 2021 season. Older seasons are also available

``` r
options(tibble.print_min=25)
nflreadr::load_schedules(2021) |> 
  dplyr::select(game_id, old_game_id, gsis)
#> # A tibble: 272 x 3
#>    game_id         old_game_id  gsis
#>    <chr>           <chr>       <int>
#>  1 2021_01_DAL_TB  2021090900  58503
#>  2 2021_01_PHI_ATL 2021091200  58504
#>  3 2021_01_PIT_BUF 2021091201  58505
#>  4 2021_01_NYJ_CAR 2021091202  58506
#>  5 2021_01_MIN_CIN 2021091203  58507
#>  6 2021_01_SF_DET  2021091204  58508
#>  7 2021_01_JAX_HOU 2021091205  58509
#>  8 2021_01_SEA_IND 2021091206  58510
#>  9 2021_01_ARI_TEN 2021091207  58511
#> 10 2021_01_LAC_WAS 2021091208  58512
#> 11 2021_01_CLE_KC  2021091209  58513
#> 12 2021_01_MIA_NE  2021091210  58514
#> 13 2021_01_GB_NO   2021091211  58515
#> 14 2021_01_DEN_NYG 2021091212  58516
#> 15 2021_01_CHI_LA  2021091213  58517
#> 16 2021_01_BAL_LV  2021091300  58518
#> 17 2021_02_NYG_WAS 2021091600  58519
#> 18 2021_02_NO_CAR  2021091908  58520
#> 19 2021_02_CIN_CHI 2021091906  58521
#> 20 2021_02_HOU_CLE 2021091907  58522
#> 21 2021_02_LA_IND  2021091904  58523
#> 22 2021_02_DEN_JAX 2021091901  58524
#> 23 2021_02_BUF_MIA 2021091902  58525
#> 24 2021_02_NE_NYJ  2021091900  58526
#> 25 2021_02_SF_PHI  2021091903  58527
#> # ... with 247 more rows
```
