### ISSUE TITLE
return_team missing in "2021_01_SF_DET"

### ISSUE THREAD

**Issue by ak47twq** [nflverse/nflfastR#275]
return_team missing in "2021_01_SF_DET"
seasonnum1 <- 2021
seasonnum2 <- 2021
weeknum1 <- 1
weeknum2 <- 1
RETURN_TD<-pbp%>%
     filter(season>=seasonnum1, season<=seasonnum2, week>=weeknum1, week<=weeknum2, return_touchdown==1) %>%
	 select(game_id,season, week, qtr, down, posteam, time, yrdln, ydstogo, desc, play_type, return_team, return_yards, return_touchdown, yards_gained, posteam_score, defteam_score, total, spread_line ) %>%
	 collect()

output like:
desc:(1:20) (Shotgun) 16-J.Goff pass short middle intended for 88-T.Hockenson INTERCEPTED by 57-D.Greenlaw [55-D.Ford] at DET 39. 57-D.Greenlaw for 39 yards, TOUCHDOWN.
play_type:pass
return_team:NA

i wonder if the return_team should be SF?

**Comment by guga31bb** [comment]
Need to add return team to stat ID 26 like it's there in 25: https://github.com/nflverse/nflfastR/blob/master/R/helper_tidy_play_stats.R#L172
