### ISSUE TITLE
NFL 2021 Week 01 Miscellaneous Errata

### ISSUE THREAD

**Issue by JoeMarino2021** [nflverse/nflfastR#276]
I used the following this evening (9/15/2021) to load the current 2021 data.

`nflfastR::load_pbp(2021)`

I discovered the following errors for data in Week 1.

- The `stadium` field is broken for many games
- In CLE-KC, on `play_id` 514, offsetting penalties is labeled as a penalty on CLE (this is a play with no accepted penalty)
- In JAX-HOU, on `play_id` 3467, the defensive pass interference for JAX is listed as 0 yards; it is a 13 yard penalty
- In NYJ-CAR, `play_id` 3490 is missing from the database
- In PHI-ATL, `play_id` 4163 is missing from the database

Is it better to scrape during the season than to use the repository?  Would scraping the data have collected an updated version of the above?  Is this just a stale data problem (with the NFL posting corrections since the repository was updated with Week 1 data)?

**Comment by guga31bb** [comment]
I think these should be fixed- we have an automatic re-fetch from NFL overnight Wed and it looks like that resolved all of these by getting the updated data. Let us know if that isn't right- thanks!

**Comment by JoeMarino2021** [comment]
Will check it when I get the chance.  Thanks for taking a look.

So, if I want the data before Thursday (so I can do my data crunching before Thursday Night Football), would it be better to scrape the data than to use the repo?

**Comment by JoeMarino2021** [comment]
Maybe you can do an automatic update on Tuesday night, too?

**Comment by JoeMarino2021** [comment]
The errors cleared up when the data refreshed on Wednesday night.  Thanks.

Is a scrape recommended during the season to get the most up to date data?  Can a Tuesday night fetch be scheduled?

Thanks for all the outstanding work!
