### ISSUE TITLE
Can nflfastr add 3 new columns:"defensive_touchdown","special_teams_touchdown"and "offensive_touchdown"?

### ISSUE THREAD

**Issue by ak47twq** [nflverse/nflfastR#280]
Can nflfastr add 3 new columns:"defensive_touchdown","special_teams_touchdown"and "offensive_touchdown"?

Cos when a punt block happened and ended with a def touchdown, it is not marked a return touchdown.
Now i use "success" and "touchdown" to see if a touchdown is def/special team touchdown.
Thx.

**Comment by guga31bb** [comment]
This is a combination of existing columns so probably won't implement
