### ISSUE TITLE
something weird about "play_type" and "play_type_nfl"

### ISSUE THREAD

**Issue by ak47twq** [nflverse/nflfastR#281]
i try to find some funny play and i found some plays "play_type" and "play_type_nfl" do not match other plays
```
int_and_fumble_lost<-pbp%>%
     filter(season>=0, season<=8888, week>=0, week<=99, interception==1, fumble_lost==1) %>%
	 select(play_id, game_id,season, week, qtr, time, posteam, desc, play_type, play_type_nfl, interception, fumble, fumble_lost, touchdown)%>%
	 collect()	 

field_goal_self_TD<-pbp%>%
     filter(season>=0, season<=8888, week>=0, week<=99, field_goal_attempt==1, touchdown==1, td_team==posteam) %>%
	 select(play_id, game_id,season, week, qtr, time, posteam, td_team, desc, play_type, play_type_nfl, kick_distance, field_goal_result, field_goal_attempt, fumble, fumble_lost, touchdown,return_team, return_yards)%>%
	 collect()
	 
field_goal_def_TD<-pbp%>%
     filter(season>=0, season<=8888, week>=0, week<=99, field_goal_attempt==1, touchdown==1, td_team!=posteam) %>%
	 select(play_id, game_id,season, week, qtr, time, posteam, td_team, desc, play_type, play_type_nfl, kick_distance, field_goal_result, field_goal_attempt, fumble, fumble_lost, touchdown,return_team, return_yards)%>%
	 collect()

punt_self_TD<-pbp%>%
     filter(season>=0, season<=8888, week>=0, week<=99, punt_attempt==1, touchdown==1, td_team==posteam) %>%
	 select(play_id, game_id,season, week, qtr, time, posteam, td_team, desc, play_type, play_type_nfl, kick_distance, punt_blocked, punt_attempt, fumble, fumble_lost, touchdown,return_team, return_yards,)%>%
	 collect()

punt_def_TD<-pbp%>%
     filter(season>=0, season<=8888, week>=0, week<=99, punt_attempt==1, touchdown==1, td_team!=posteam) %>%
	 select(play_id, game_id,season, week, qtr, time, posteam, td_team, desc, play_type, play_type_nfl, kick_distance, punt_blocked, punt_attempt, fumble, fumble_lost, touchdown,return_team, return_yards,)%>%
	 collect()	
```
in `int_and_fumble_lost `
![6](https://user-images.githubusercontent.com/72854702/134189971-0f9ec81a-ac3c-4aad-8ae0-cb08106de2e7.JPG)
play_id  game_id
1720  1999_03_CLE_BAL
1165  1999_14_CAR_GB
3101  2000_06_WAS_PHI
4927  2000_08_MIA_NYJ
925  2000_11_NO_CAR

in `field_goal_def_TD`
![7](https://user-images.githubusercontent.com/72854702/134190658-371e7aed-6711-4406-8ac0-89ef166f9727.JPG)
![8](https://user-images.githubusercontent.com/72854702/134190689-cfe8d3e4-b098-47ac-888b-8a549da177b0.JPG)
3512  1999_18_DET_WAS
2835  2000_06_TB_MIN
3541  2000_16_SD_CAR
2639  2000_19_BAL_TEN
3142  2002_17_MIN_DET
1668  2004_13_TEN_IND
3636  2006_10_CHI_NYG
577  2008_05_MIN_NO
1047  2009_02_ARI_JAX
732  1999_08_SEA_GB

in `punt_self_TD`
![9](https://user-images.githubusercontent.com/72854702/134191408-c2068e77-146b-46da-a8d1-0900f2d5b20d.JPG)
1066  2000_16_DEN_KC

in `punt_def_TD`
![10](https://user-images.githubusercontent.com/72854702/134191756-97de22b8-403b-4b8d-96d7-3ce1f0097fe8.JPG)

**Comment by ak47twq** [comment]
```
kickoff_self_TD<-pbp%>% 
	 filter(season>=0, season<=8888, week>=0, week<=99, kickoff_attempt==1, touchdown==1, td_team!=posteam) %>%
	 select(play_id, game_id,season, week, qtr, time, posteam, td_team, desc, play_type, play_type_nfl, kick_distance, fumble, fumble_lost, own_kickoff_recovery, touchdown, own_kickoff_recovery_td, return_team, return_yards)%>%
	 collect()
	 
kickoff_def_TD<-pbp%>% 
	 filter(season>=0, season<=8888, week>=0, week<=99, kickoff_attempt==1, touchdown==1, td_team==posteam) %>%
	 select(play_id, game_id,season, week, qtr, time, posteam, td_team, desc, play_type, play_type_nfl, kick_distance, fumble, fumble_lost, own_kickoff_recovery, touchdown, own_kickoff_recovery_td, return_team, return_yards)%>%
	 collect()
```

i found that 1999 season and 2000 season, the `play_type_nfl` is all NA.

**Comment by guga31bb** [comment]
- `play_type_nfl` being NA for 1999 and 2000 is because the data source we have for 2001+ (which is what has `play_type_nfl`) doesn't include those seasons
- These two columns aren't expected to match: `play_type_nfl` is provided directly from NFL, while `play_type` was intended to replicate `nflscrapR`

Looking at this, I think there's a bug in `play_type` where it's incorrectly `no_play` on blocked punts/FGs

**Comment by ak47twq** [comment]
ok THX！
