### ISSUE TITLE
Update Rams Color Scheme

### ISSUE THREAD

**Issue by mrcaseb** [nflverse/nflfastR#290]
It looks like we should update the Rams colors

**Comment by guga31bb** [comment]
I think I'd be in favor of changing all of these to update to the new version except Seahawks secondary

**Comment by brunomioto** [comment]
+1 for @guga31bb and @ajreinhard suggestions!

**Comment by mrcaseb** [comment]
> 
> 
> I think `LAC` could use yellow, because you know, Chargers. Lighter blue `#0081c9` with gold `#ffaf00`, maybe? (From logo)

I thought about this as @ajreinhard mentioned it but it would be **very** close to the Rams imo
