### ISSUE TITLE
something strange about play_id"890",game_id"2021_04_HOU_BUF"

### ISSUE THREAD

**Issue by ak47twq** [nflverse/nflfastR#294]
```
bug<-pbp%>%
	 filter(desc=="END QUARTER 1",season==2021, week<=4)%>%
	  select(play_id,game_id,season,week,posteam,down,yardline_100,desc,fixed_drive,fixed_drive_result,drive_inside20,yards_gained,drive_start_yard_line, drive_end_yard_line)%>%
	 collect()
```
all other `END QUARTER 1` has NA for `yardline_100`
play_id`890` has 50 for `yardline_100`

**Comment by tanho63** [comment]
Hmm, I don’t see this as being particularly concerning and probably will mark as a wontfix unless it’s demonstrably road blocking someone’s analysis
