### ISSUE TITLE
Off-by-1 bug in total_home_score and total_away_score

### ISSUE THREAD

**Issue by alecglen** [nflverse/nflfastR#300]
[The field definitions](https://www.nflfastr.com/articles/field_descriptions.html) for `total_home_score` and `total_away_score` state that they should contain the scores as of the beginning of the play.

Instead, comparison to the fields `posteam_score` and `defteam_score` shows that they actually contain the scores as of the end of the play. (Please pardon the lack of of reprex, I'm not an R user.)

```
play_by_play.loc[
    play_by_play['game_id'] == '2021_01_ARI_TEN',
    [
        'play_id', 'desc', 'posteam', 'posteam_type', 'sp', 'total_home_score', 'total_away_score',
        'posteam_score', 'defteam_score', 'posteam_score_post', 'defteam_score_post'
    ]
].iloc[14:30]
```
![image](https://user-images.githubusercontent.com/28493454/139562588-40d9e7bd-8de8-4297-9c9f-d54ab1fa3645.png)

**Comment by mrcaseb** [comment]
Looks like a documentation bug inherited from nflscrapR. These variables are supposed to be post play as far as I can remember.
