### ISSUE TITLE
Inconsistencies with POSTEAM

### ISSUE THREAD

**Issue by awgymer** [nflverse/nflfastR#33]
Just looking through the data and after running `update_db` and inspecting the whole dataset I discovered that there are three plays with `play_id = 2323` `game_id = 2000_11_OAK_DEN` where the `name` is listed as `T.Davis` (Terrell Davis) but the `posteam` is `LV`. 

I'm not sure what the cause of this is, or if it affects other plays/games.

**Comment by guga31bb** [comment]
This is an example of duplicated `play_id` in older seasons which causes errors because we don't know which stat IDs are supposed to correspond to which play. I wonder if we should just remove this game from `nflfastR` like we had to with a couple others in this season:
``` r
g <- fast_scraper('2000_11_OAK_DEN') %>%
  clean_pbp()

g %>% 
  filter(play_id == 2323) %>%
  select(posteam, desc, name)

# A tibble: 4 x 3
  posteam desc                                                                                    name    
  <chr>   <chr>                                                                                   <chr>   
1 LV      (8:49) B.Griese pass to E.McCaffrey to OAK 4 for 2 yards (G.Biekert).                   B.Griese
2 LV      (8:06) T.Davis right guard to OAK 5 for -1 yards (R.Coleman, T.Bryant).                 T.Davis 
3 LV      (7:29) J.Elam 23 yard field goal is GOOD, Center-M.Lepsis, Holder-T.Rouen.              T.Davis 
4 LV      J.Elam kicks 53 yards from DEN 30 to OAK 17. D.Dunn to OAK 29 for 12 yards (G.Coghill). T.Davis 
```

**Comment by awgymer** [comment]
I see. Just ran a quick check and it looks like this issue affects 9 plays across 8 games:

```
> pbp[,.N, by="game_id,play_id"][N>1]
           game_id play_id N
1: 2000_03_PIT_CLE    2768 2
2: 2000_03_PIT_CLE    2767 2
3: 2000_06_WAS_PHI    1825 4
4: 2000_11_OAK_DEN    2323 4
5: 2002_03_DAL_PHI    3635 2
6:  2002_05_KC_NYJ    1020 2
7: 2005_04_SEA_WAS    2861 3
8:  2006_10_TB_CAR     103 3
9: 2007_08_IND_CAR    4382 9
```

Personally I'd typically be inclined to try and keep as much data as possible with exceptions/workarounds but I don't really know how convoluted that becomes for this case.

**Comment by mrcaseb** [comment]
Closing this as it's documented for several years that this won't be fixed
