### ISSUE TITLE
Error pulling prior rosters

### ISSUE THREAD

**Issue by rwj5023** [nflverse/nflfastR#352]
> roster_dat <- fast_scraper_roster(c(2015:2022))
ℹ It is recommended to use parallel processing when trying to load multiple seasons. Please consider running `future::plan("multisession")`! Will go on sequentially...
Warning: Either the requested season 2015 is invalid or no data available at this time!
Warning: Either the requested season 2016 is invalid or no data available at this time!
Warning: Either the requested season 2017 is invalid or no data available at this time!
Warning: Either the requested season 2018 is invalid or no data available at this time!
Warning: Either the requested season 2019 is invalid or no data available at this time!
Warning: Either the requested season 2020 is invalid or no data available at this time!
Warning: Either the requested season 2021 is invalid or no data available at this time!
Warning: Either the requested season 2022 is invalid or no data available at this time!
Error in `chr_as_locations()`:
! Can't rename columns that don't exist.
✖ Column `gsis_id` doesn't exist.
Run `rlang::last_error()` to see where the error occurred.
> rlang::last_error()
<error/vctrs_error_subscript_oob>
Error in `chr_as_locations()`:
! Can't rename columns that don't exist.
✖ Column `gsis_id` doesn't exist.
---
Backtrace:
  1. ... %>% filter(position %in% c("QB", "RB", "WR", "TE", "K"))
  7. dplyr:::rename.data.frame(., player_id = gsis_id)
  8. tidyselect::eval_rename(expr(c(...)), .data)
  9. tidyselect:::rename_impl(...)
 10. tidyselect:::eval_select_impl(...)
 19. tidyselect:::vars_select_eval(...)
 20. tidyselect:::walk_data_tree(expr, data_mask, context_mask, error_call)
 21. tidyselect:::eval_c(expr, data_mask, context_mask)
 22. tidyselect:::reduce_sels(node, data_mask, context_mask, init = init)
 23. tidyselect:::walk_data_tree(new, data_mask, context_mask)
 24. tidyselect:::as_indices_sel_impl(...)
 25. tidyselect:::as_indices_impl(x, vars, call = call, strict = strict)
 26. tidyselect:::chr_as_locations(x, vars, call = call)
Run `rlang::last_trace()` to see the full context.

**Comment by tanho63** [comment]
Hello! Please fill out the bug report template when reporting bugs. You can find it here: https://github.com/nflverse/nflfastR/issues/new/choose
