### ISSUE TITLE
The multiple laterals file should be hosted in a nflverse repo

### ISSUE THREAD

**Issue by mrcaseb** [nflverse/nflfastR#356]
https://github.com/nflverse/nflfastR/blob/0fa754dda504b133e03885f6ef53bf8e21a56276/R/aggregate_game_stats.R#L100

Any suggestions where to host it @tanho63? It needs to be updated daily through GHA.

**Comment by tanho63** [comment]
Also teamcolorslogos. nflverse-data/misc ?

**Comment by mrcaseb** [comment]
I'd like to have version control on both of them. However, we could release them additionally in nflverse-data/misc to be consistent

**Comment by tanho63** [comment]
So what we should do is have it attached to nflverse-data misc but automatically pushed by GHA when the version control is updated

-
Tan Ho
________________________________

**Comment by mrcaseb** [comment]
> So what we should do is have it attached to nflverse-data misc but automatically pushed by GHA when the version control is updated - Tan Ho
> […](#)

In another repo, right?

**Comment by mrcaseb** [comment]
Going to be resolved in https://github.com/nflverse/nflverse-pbp/pull/63
