### ISSUE TITLE
Issue Running Calculate_Player_Stats using pbp data on nflfastR

### ISSUE THREAD

**Issue by marvin3FF** [nflverse/nflfastR#358]
1. **Have you installed the latest development version of the package(s) in question? **

2. **Describe the bug**3. 

Hello! I'm not sure if anyone has run into this issue yet. I am running the **calculate_player_stats** function using play-by-play data. In the past, it would run without any errors or issues, but recently came across this error:

*Warning message:
Failed to parse file with qs::qdeserialize() from <https://github.com/nflverse/nflfastR-roster/raw/master/data/nflfastR-RB_ids.qs> *

At first glance, I don't see any issues with the data. However, I figured I'd send this over in case there is something wrong. I've also attached an image of the error. Let me know if you need anything else! 

Thanks so much,

Marvin

4. **Reprex**

```r

# put code here

```

5. **Expected Behaviour**

6. **nflverse_sitrep()**

<details>
  <summary> sitrep </summary>
  
  ```r
  # nflverse_sitrep() goes here

  ```
</details>

7. **Screenshots**

8. **Additional context**

**Comment by mrcaseb** [comment]
Resolved in #357
