### ISSUE TITLE
td_player_id is wrong when retrieving pbp data using build_nflfastR_pbp

### ISSUE THREAD

**Issue by iorparask** [nflverse/nflfastR#362]
When retrieving pbp data for 2022 using 
pbp <- build_nflfastR_pbp("2022_01_BUF_LA")

column 53 (td_player_id) has "garbage" data, for example:

DAV2<96>u8<f5>> 
for G.Davis

or 

KUPSE<97><b9>X<87>@
for C.Kupp

**Comment by tanho63** [comment]
Have you updated to latest devel version? We were working on it this morning

**Comment by guga31bb** [comment]
Please update nflfastR or use nflreadr:

```
> nflreadr::load_pbp(2022) %>% filter(!is.na(td_player_id)) %>% select(td_player_id)
── nflverse play by play data ───────────────────────────────────────────────────────────────
ℹ Data updated: 2022-09-09 13:16:58 EDT
# A tibble: 5 × 1
  td_player_id
  <chr>       
1 00-0036196  
2 00-0033908  
3 00-0033466  
4 00-0034857  
5 00-0031588 
```

**Comment by iorparask** [comment]
Thank you, worked fine with the dev version.
@guga31bb at first I used nflreadr but there were some issues with updating the repository (which are resolved now btw). Will wait for the next games to make sure.
