### ISSUE TITLE
pbp.. Kick_distance

### ISSUE THREAD

**Issue by Cityviewsound** [nflverse/nflfastR#392]
In PBP.. Kick_Distance only shows a value when the kickoff is not a touchback. please show a value for all kickoffs. If the kickoff starts On the 35, and the kick is a touchback, the kick distance would be 50 yards.

**Comment by tanho63** [comment]
Related to #53-ish.

**Comment by mrcaseb** [comment]
For future reference: final fix of this issue happened in #422 by using the corresponding stat IDs
