### ISSUE TITLE
Add `receive_2h_ko` as variable

### ISSUE THREAD

**Issue by 903124** [nflverse/nflfastR#409]
1. **Is your feature request related to a problem? Please describe.**
In WP calculator `receive_2h_ko` is used as input variable but not exist in the data. Other variables however are already existing in the feed

2. **Describe the solution you'd like**
Per @guga31bb 

        model_data <- pbp_data %>%
       dplyr::mutate(
        receive_2h_ko = case_when(
          # 1st half, home team opened game with kickoff, away team has ball
          qtr <= 2 & home_opening_kickoff == 1 & posteam == away_team ~ 1,
          # 1st half, away team opened game with kickoff, home team has ball
          qtr <= 2 & home_opening_kickoff == 0 & posteam == home_team ~ 1,
          TRUE ~ 0
        )     
       )

3. **Describe alternatives you've considered**
Instead using the code above manually

4. **Additional context**
I should submit a pull request but I don't really use R :joy:

**Comment by mrcaseb** [comment]
The dataset already is big and `receive_2h_ko` can easily be computed with the above code snippet. So we won't add this.
