### ISSUE TITLE
[BUG] <title> play clock data error

### ISSUE THREAD

**Issue by RicShern** [nflverse/nflfastR#443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you installed the latest development version of the package(s) in question?

- [X] I have installed the latest development version of the package.

### If this is a data issue, have you tried clearing your nflverse cache?

I have cleared my nflverse cache and the issue persists.

### What version of the package do you have?

1.0.3

### Describe the bug

The play_clock data seems wrong in 2023 season pbp database. 
Every play_clock starts at 0.

### Reprex

```r
> pbp23%>%group_by(play_clock)%>%summarize(n=n())
# A tibble: 1 × 2
  play_clock     n
  <chr>      <int>
1 0          21395
```

### Expected Behavior

> pbp22%>%select(play_clock)
── nflverse play by play data ───────────────────────────────────────────────────────────────────────────────────
ℹ Data updated: 2023-02-13 17:22:54 CST
# A tibble: 50,147 × 1
   play_clock
   <chr>     
 1 0         
 2 0         
 3 13        
 4 23        
 5 23        
 6 24        
 7 10        
 8 14        
 9 26        
10 6         
# ℹ 50,137 more rows

### nflverse_sitrep

```r
# A tibble: 1 × 2
  play_clock     n
  <chr>      <int>
1 0          21395
```

**Comment by guga31bb** [comment]
This is an NFL-provided field so there's nothing we can do on our end
