### ISSUE TITLE
[BUG] nflreadr::load_participation() only loads a subset of week 14/15/16 data

### ISSUE THREAD

**Issue by jreddy1990** [nflverse/nflfastR#450]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you installed the latest development version of the package(s) in question?

- [X] I have installed the latest development version of the package.

### If this is a data issue, have you tried clearing your nflverse cache?

I have cleared my nflverse cache and the issue persists.

### What version of the package do you have?

function doesn't work

### Describe the bug

missing 95% of expected pbp records; subset of pbp for weeks 14/15/16 is returned

### Reprex

```r
nflreadr::load_participation(
    seasons = nflreadr::most_recent_season(),
    include_pbp = TRUE
  )
```

### Expected Behavior

all weeks, all plays for all games

### nflverse_sitrep

```r
── System Info ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
• R version 4.3.2 (2023-10-31) • Running under: macOS Sonoma 14.0
── Package Status ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   package installed  cran        dev behind
1 nflfastR     4.6.0 4.6.0 4.6.0.9000    dev
2 nflreadr     1.4.0 1.4.0   1.4.0.11    dev
── Package Options ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
• No options set for above packages
── Package Dependencies ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
• cachem      (1.0.8)   • grid       (4.3.2)    • purrr      (1.0.2)    
• cli         (3.6.1)   • hms        (1.1.3)    • R6         (2.5.1)    
• codetools   (0.2-19)  • janitor    (2.2.0)    • rappdirs   (0.3.3)    
• compiler    (4.3.2)   • jsonlite   (1.8.7)    • rlang      (1.1.2)    
• cpp11       (0.4.6)   • lattice    (0.21-9)   • snakecase  (0.11.1)   
• curl        (5.1.0)   • lifecycle  (1.0.4)    • splines    (4.3.2)    
• data.table  (1.14.8)  • listenv    (0.9.0)    • stats      (4.3.2)    
• digest      (0.6.33)  • lubridate  (1.9.3)    • stringi    (1.8.2)    
• dplyr       (1.1.4)   • magrittr   (2.0.3)    • stringr    (1.5.1)    
• fansi       (1.0.5)   • Matrix     (1.6-1.1)  • tibble     (3.2.1)    
• fastmap     (1.1.1)   • memoise    (2.0.1)    • tidyr      (1.3.0)    
• fastrmodels (1.0.2)   • methods    (4.3.2)    • tidyselect (1.2.0)    
• furrr       (0.3.1)   • mgcv       (1.9-0)    • timechange (0.2.0)    
• future      (1.33.0)  • nlme       (3.1-163)  • tools      (4.3.2)    
• generics    (0.1.3)   • parallel   (4.3.2)    • utf8       (1.2.4)    
• globals     (0.16.2)  • parallelly (1.36.0)   • utils      (4.3.2)    
• glue        (1.6.2)   • pillar     (1.9.0)    • vctrs      (0.6.4)    
• graphics    (4.3.2)   • pkgconfig  (2.0.3)    • withr      (2.5.2)    
• grDevices   (4.3.2)   • progressr  (0.14.0)   • xgboost    (1.7.5.1)  
── Not Installed ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
• nflseedR  • nflplotR    
• nfl4th    • nflverse    
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

**Comment by jreddy1990** [comment]
this still has issues

<img width="456" alt="image" src="https://github.com/nflverse/nflfastR/assets/12733851/f3e40929-d846-41a7-8a04-56208ca48d7c">

**Comment by huskerfly** [comment]
Issue is still occurring - please institute a fix. For Week 15, for example, only the Christmas Day games populate.

**Comment by tanho63** [comment]
no amount of messaging here will fix an API side issue. Solving will take an indeterminate amount of time.

**Comment by huskerfly** [comment]
> no amount of messaging here will fix an API side issue. Solving will take an indeterminate amount of time.

Understood - thank you for the quick update. Only 3 games have populated for Weeks 16 / 17 for load_participation. load_pbp populates just fine. Is there someone else that we can go to to ask for updates?

**Comment by tanho63** [comment]
There is nobody across the nflverse development team nor the public analytics community who has insight into if/when non-primetime games will be available from the NGS API. 

We are not affiliated with them and are beholden to what is provided as public access.

**Comment by huskerfly** [comment]
That is disappointing to read - do you think that there is anyone that can be contacted to learn why / make any changes?
