### ISSUE TITLE
[BUG] punter_player_id and punter_player_name are NULL when punt_blocked  = 1

### ISSUE THREAD

**Issue by andrewtek** [nflverse/nflfastR#462]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you installed the latest development version of the package(s) in question?

- [X] I have installed the latest development version of the package.

### If this is a data issue, have you tried clearing your nflverse cache?

I am not using an nflverse R package (nflreadr, nflfastR) to access this data.

### What version of the package do you have?

N/A

### Describe the bug

When checking data for 2023, punter_player_id and punter_player_name are null when punt_blocked = 1. 

It appears that these pieces of information are available in the raw stat data, but they are stored on statId 2. 

![image](https://github.com/nflverse/nflfastR/assets/962294/187c02a5-37ea-4d51-9d94-335fb2777108)

### Reprex

```r
The following plays have this issue:

game_id    play_id
2023_05_BAL_PIT    3146
2023_08_LA_DAL    1014
2023_13_IND_TEN    3369
2023_15_PIT_IND    902
2023_16_WAS_NYJ    356
2023_18_DAL_WAS    2671
```

### Expected Behavior

I would expect punter_player_id and punter_player_name to contain the id and name of the punting player. These values appear to exist in the raw play stats on statId 2.

### nflverse_sitrep

```r
NA
```

**Comment by mrcaseb** [comment]
Confirmed. We don't right player information for stat ID == 2. 

I also found some time to cross check other stat IDs. The following stat IDs at least occasionally provide player information while we don't write any of them. 

- [ ] 2
- [ ] 57
- [ ] 61
- [ ] 63
- [ ] 64
- [ ] 402
- [ ] 403
- [ ] 404

This is just the list of IDs where we don't write player info while we could. I have not yet checked whether this is reasonable or not.
