### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by rjthompson2** [nflverse/nflfastR#487]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you installed the latest development version of the package(s) in question?

- [X] I have installed the latest development version of the package.

### If this is a data issue, have you tried clearing your nflverse cache?

This is not a data-related issue.

### What version of the package do you have?

N/A

### Describe the bug

The url "https://github.com/nflverse/nflverse-data/releases/download/pbp_participation/pbp_participation_2024.parquet" does not exist. Will this be fixed or has it been deprecated? If it has been deprecated what should I do instead? Thank you!

### Reprex

```r
https://github.com/nflverse/nflverse-data/releases/download/pbp_participation/pbp_participation_2024.parquet

https://github.com/nflverse/nflverse-data/releases/download/pbp_participation/pbp_participation_2023.parquet
```

### Expected Behavior

I expected to download the parquet of 2024 play by play data

### nflverse_sitrep

```r
N/A
```

**Comment by tanho63** [comment]
no participation data in 2024, see: https://x.com/John_B_Edwards/status/1832091502895579354
